/**
 * SQL MIGRATION: Paste into Supabase SQL Editor to support contract-aware events and user feedback:
 *
 * -- Table: feedback
 * create table if not exists feedback (
 *   id uuid default gen_random_uuid() primary key,
 *   rating integer not null,
 *   comment text,
 *   wallet_address text,
 *   page text,
 *   created_at timestamptz default now()
 * );
 *
 * -- Row Level Security Policies for feedback:
 * alter table feedback enable row level security;
 * create policy "Allow public inserts" on feedback for insert with check (true);
 * create policy "Allow public selects" on feedback for select using (true);
 *
 * -- Table: circle_events
 * create table if not exists circle_events (
 *   id bigint generated by default as identity primary key,
 *   contract_id text,
 *   circle_id text not null,
 *   event_type text not null,
 *   wallet_address text,
 *   amount_xlm numeric,
 *   tx_hash text,
 *   details jsonb default '{}'::jsonb,
 *   created_at timestamptz default now()
 * );
 *
 * -- Migration for existing tables:
 * alter table circle_events add column if not exists contract_id text;
 *
 * -- Backfill existing legacy rows (which have null contract_id) with legacy contract ID:
 * update circle_events
 * set contract_id = 'CAY3GCWDFCXPU6JEIJAECX5UXWKXSKO5WTAV3QUFXFXRV4USNQ2FKLO4'
 * where contract_id is null;
 *
 * -- Index for performant contract_id + circle_id lookup:
 * create index if not exists idx_circle_events_contract_circle
 * on circle_events (contract_id, circle_id);
 *
 * -- Row Level Security Policies for circle_events:
 * alter table circle_events enable row level security;
 * create policy "Allow public inserts" on circle_events for insert with check (true);
 * create policy "Allow public selects" on circle_events for select using (true);
 * alter publication supabase_realtime add table circle_events;
 */

import { createClient } from "@supabase/supabase-js";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "";
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "";
const CURRENT_CONTRACT_ID = import.meta.env.VITE_SOROBAN_CONTRACT_ID || "";
const LEGACY_CONTRACT_ID = "CAY3GCWDFCXPU6JEIJAECX5UXWKXSKO5WTAV3QUFXFXRV4USNQ2FKLO4";

/**
 * Returns true only when both credentials look like real Supabase values.
 * Guards against placeholder/dummy keys making failed network requests.
 */
function isRealSupabaseConfig(url: string, key: string): boolean {
  if (!url || !key) return false;
  // URL must be a valid-looking supabase.co endpoint
  if (!url.startsWith("https://") || !url.includes(".supabase.co")) return false;
  // Key must look like a JWT: three dot-separated segments, >= 100 chars total
  const parts = key.split(".");
  if (parts.length !== 3) return false;
  if (key.length < 100) return false;
  // Reject obvious placeholders
  if (key.endsWith(".dummy") || key.toLowerCase().includes("placeholder")) return false;
  return true;
}

const CLIENT_READY = isRealSupabaseConfig(SUPABASE_URL, SUPABASE_ANON_KEY);

export const supabase = CLIENT_READY ? createClient(SUPABASE_URL, SUPABASE_ANON_KEY) : null;

export interface FeedbackData {
  wallet_address?: string | null;
  rating: number;
  comment?: string;
  page?: string;
}

/**
 * Insert a feedback row into the Supabase `feedback` table.
 */
export async function submitFeedbackToSupabase(data: FeedbackData): Promise<boolean> {
  if (!supabase) {
    console.log("[Rotera Feedback] Supabase not configured — logged locally:", data);
    return false;
  }

  try {
    const { error } = await supabase.from("feedback").insert([
      {
        wallet_address: data.wallet_address ?? null,
        rating: data.rating,
        comment: data.comment?.trim() ?? "",
        page: data.page ?? (typeof window !== "undefined" ? window.location.pathname : "/"),
        created_at: new Date().toISOString(),
      },
    ]);

    if (error) {
      console.error("[Rotera Feedback] Insert error:", error.message, error.code);
      return false;
    }

    return true;
  } catch (err) {
    console.error("[Rotera Feedback] Unexpected error:", err);
    return false;
  }
}

// ─── Circle Event & History Tracking ─────────────────────────────────────────

export interface CircleEventRecord {
  id?: number;
  contract_id?: string | null;
  circle_id: string;
  event_type:
    | "circle_created"
    | "circle_joined"
    | "contribution"
    | "cycle_closed"
    | "debt_repaid"
    | "deposit_withdrawn";
  wallet_address?: string | null;
  amount_xlm?: number | null;
  tx_hash?: string | null;
  details?: Record<string, any>;
  created_at?: string;
}

/**
 * Record a circle event (create, join, contribute, close cycle, repay debt) to Supabase.
 * Injects contract_id both as a top-level column and inside details for forward & backward schema compatibility.
 */
export async function recordCircleEventToSupabase(event: CircleEventRecord): Promise<boolean> {
  if (!supabase) return false;

  const contractId = event.contract_id || CURRENT_CONTRACT_ID || null;
  const payloadDetails = {
    ...(event.details || {}),
    contract_id: contractId,
  };

  try {
    // 1. Try inserting with contract_id column
    const { error } = await supabase.from("circle_events").insert([
      {
        contract_id: contractId,
        circle_id: String(event.circle_id),
        event_type: event.event_type,
        wallet_address: event.wallet_address ?? null,
        amount_xlm: event.amount_xlm ?? null,
        tx_hash: event.tx_hash ?? null,
        details: payloadDetails,
        created_at: event.created_at || new Date().toISOString(),
      },
    ]);

    if (error) {
      // If contract_id column doesn't exist yet in the database schema cache, fallback to inserting without top-level column
      if (
        error.message?.includes("contract_id") ||
        error.code === "42703" ||
        error.code === "PGRST204"
      ) {
        const { error: fallbackErr } = await supabase.from("circle_events").insert([
          {
            circle_id: String(event.circle_id),
            event_type: event.event_type,
            wallet_address: event.wallet_address ?? null,
            amount_xlm: event.amount_xlm ?? null,
            tx_hash: event.tx_hash ?? null,
            details: payloadDetails,
            created_at: event.created_at || new Date().toISOString(),
          },
        ]);
        if (fallbackErr) {
          console.warn("[Rotera Supabase Event Fallback] Insert error:", fallbackErr.message);
          return false;
        }
        return true;
      }
      console.warn("[Rotera Supabase Event] Insert error:", error.message);
      return false;
    }

    return true;
  } catch (err) {
    console.warn("[Rotera Supabase Event] Unexpected error:", err);
    return false;
  }
}

/**
 * Fetch historical events for a circle (or all circles) from Supabase for a specific contract.
 */
export async function fetchCircleEventsFromSupabase(
  circleId?: string | number | null,
  targetContractId?: string | null,
): Promise<CircleEventRecord[]> {
  if (!supabase) return [];

  const contractId = targetContractId ?? (CURRENT_CONTRACT_ID || "");

  try {
    // 1. Attempt querying with contract_id column filter
    if (contractId) {
      let contractQuery = supabase
        .from("circle_events")
        .select("*")
        .eq("contract_id", contractId)
        .order("created_at", { ascending: false });

      if (circleId) {
        contractQuery = contractQuery.eq("circle_id", String(circleId));
      }

      const { data, error } = await contractQuery;
      if (!error && data) {
        if (import.meta.env.DEV) {
          console.log(
            `[Supabase] ${data.length} events for contract=${contractId.slice(0, 8)}… circle=${circleId || "all"}`,
          );
        }
        return data as CircleEventRecord[];
      }
    }

    // 2. Fallback: query by circle_id and filter by contract_id in memory (matches top-level or details.contract_id)
    let query = supabase
      .from("circle_events")
      .select("*")
      .order("created_at", { ascending: false });

    if (circleId) {
      query = query.eq("circle_id", String(circleId));
    }

    const { data, error } = await query;
    if (error || !data) {
      if (import.meta.env.DEV) {
        console.log(
          `[Supabase] 0 events for contract=${contractId ? contractId.slice(0, 8) + "…" : "all"} circle=${circleId || "all"}`,
        );
      }
      return [];
    }

    const filtered = (data as CircleEventRecord[]).filter((evt) => {
      if (!contractId) return true;
      const evtCid = evt.contract_id || evt.details?.["contract_id"];
      if (evtCid) return evtCid === contractId;
      // If event has no contract_id recorded at all, it belongs to legacy contract
      return contractId === LEGACY_CONTRACT_ID;
    });

    if (import.meta.env.DEV) {
      console.log(
        `[Supabase] ${filtered.length} events for contract=${contractId ? contractId.slice(0, 8) + "…" : "all"} circle=${circleId || "all"}`,
      );
    }

    return filtered;
  } catch (err) {
    console.warn("[Rotera Supabase Event Fetch] Error:", err);
    return [];
  }
}

/**
 * Subscribe to realtime circle events from Supabase.
 * Triggers onEvent callback whenever a new event is inserted for the given circle and contract.
 */
export function subscribeCircleEvents(
  circleId: string | number | null | undefined,
  onEvent: (event: CircleEventRecord) => void,
  targetContractId?: string | null,
): () => void {
  if (!supabase || !circleId) return () => {};

  const contractId = targetContractId ?? (CURRENT_CONTRACT_ID || "");

  try {
    const channelName = `circle_events_${contractId ? contractId.slice(0, 8) : "all"}_${circleId}`;
    const channel = supabase
      .channel(channelName)
      .on(
        "postgres_changes",
        {
          event: "INSERT",
          schema: "public",
          table: "circle_events",
          filter: `circle_id=eq.${String(circleId)}`,
        },
        (payload) => {
          if (payload.new) {
            const newEvt = payload.new as CircleEventRecord;
            const evtCid = newEvt.contract_id || newEvt.details?.["contract_id"];
            if (!contractId || !evtCid || evtCid === contractId) {
              onEvent(newEvt);
            }
          }
        },
      )
      .subscribe();

    return () => {
      supabase.removeChannel(channel);
    };
  } catch (err) {
    console.warn("[Rotera Supabase Event Subscribe] Error:", err);
    return () => {};
  }
}
